server:
  port: 8081

spring:
  application:
    name: gateway-server
    cloud:
      gateway:
        discovery:
          locator:
            enabled: false

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://discovery-server:8761/eureka/}